import commands.adminCommands
import commands.csvCommands
import commands.devCommands
import commands.serverCommands
import commands.participantCommands
import commands.registrationCommands
import commands.tournamentCommands